### ISSUE TITLE
Need a developer writeup to get started

### ISSUE THREAD

**Issue by mugunth** [kuruntham/pykalappai#2]
Need a developer guide to get new developers started. Just a short how to section in the readme file is enough.

**Comment by mohanrex** [comment]
I had started working on this documentation.
[Document link](https://www.notion.so/PyKalappai-47c43d5af9e6435a803ca02e93f38fe2) Let me know if this is good or comment on what other details would be required.

**Comment by manikk** [comment]
The initial developer documentation has been added to the Readme.md by @mohanrex. So, closing the ticket.
